ServerRoot "/usr/local/apache2"
Listen 80

# Essential Base Modules
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule unixd_module modules/mod_unixd.so

# Proxy and Balancer Modules (All 5 are required)
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
LoadModule slotmem_shm_module modules/mod_slotmem_shm.so

ServerName vensamdevops.com

<VirtualHost *:80>
    <Proxy "balancer://mycluster">
        BalancerMember "http://tomcatcont1:8080"
        BalancerMember "http://tomcatcont2:8080"
        BalancerMember "http://tomcatcont3:8080"
        BalancerMember "http://tomcatcont4:8080"
        ProxySet lbmethod=byrequests
    </Proxy>

    ProxyPass "/" "balancer://mycluster/"
    ProxyPassReverse "/" "balancer://mycluster/"
</VirtualHost>
